site_name: NFDI4Memory
site_url: https://nfdi.fiz-karlsruhe.de/4memory/
repo_url: https://github.com/ISE-FIZKarlsruhe/nfdi4memory
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: teal
    accent: pink
  features:
    - content.code.copy
    - toc.follow
    - navigation.top
    - header.autohide
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
extra_javascript:
  - javascripts/extra.js
nav:
- Home: index.md
- Data Model: data_model.md
- Ontology: ontology.md
- Sample Queries: queries.md
- Resources:
    - Academic Discipline:
      - Alte Geschichte: resource/E804
      - Archivwissenschaften: resource/E801
      - Digital Humanities: resource/E803
      - Forschungsdatenmanagement: resource/E805
      - Geistes- und Sozialwissenschaften: resource/E806
      - Geowissenschaften: resource/E802
      - Geschichte: resource/E800
    - City:
      - Amsterdam: resource/E2222
      - Berlin: resource/E2227
      - Dresden: resource/E2221
      - Garching: resource/E2228
      - Kiel: resource/E2230
      - München: resource/E2231
      - Trier: resource/E2225
    - Concept:
      - Alte Geschichte: resource/E804
      - Archivwissenschaften: resource/E801
      - Digital Humanities: resource/E803
      - Forschungsdatenmanagement: resource/E805
      - Geistes- und Sozialwissenschaften: resource/E806
      - Geowissenschaften: resource/E802
      - Geschichte: resource/E800
      - Leibniz Association: resource/E3001
      - academic library: resource/E3002
      - data center: resource/E3007
      - faculty: resource/E3003
      - library: resource/E3008
      - museum: resource/E3009
      - research institute: resource/E3000
      - state archive: resource/E3005
      - university: resource/E3004
      - university institute: resource/E3006
    - Consortium:
      - NFDI4Memory - The Consortium for the Historically Oriented Humanities: resource/E2
    - Consulting Funding:
      - FuD. Virtuelle Forschungsumgebung für die Geistes- und Sozialwissenschaften: resource/E107
    - Country:
      - Deutschland: resource/E2224
    - Data Portal:
      - Deutsche Historische Bibliografie (DHB): resource/E112
      - Oral-History.Digital. Interviewportal - Erschließungsplattform - Forschungsumgebung: resource/E108
      - Portal der European Holocaust Research Infrastructure (EHRI): resource/E100
      - Virtuelles Kartenforum: resource/E101
      - eAQUA: resource/E103
    - Dataset:
      - Forschungsdatenrepositorium Trier (FRET): resource/E105
      - xTree Vokabularverwaltung für 200+ Vokabulare/Teilvokabulare: resource/E110
    - Federal State:
      - Bayern: resource/E2229
      - Berlin: resource/E2227
      - Rheinland-Pfalz: resource/E2226
      - Sachsen: resource/E2223
    - Information Documentation:
      - FuD. Virtuelle Forschungsumgebung für die Geistes- und Sozialwissenschaften: resource/E107
    - Learning Teaching:
      - FuD. Virtuelle Forschungsumgebung für die Geistes- und Sozialwissenschaften: resource/E107
    - License:
      - Apache 2.0: resource/E503
      - Creative Commons: resource/E502
      - Creative Commons CC0: resource/E501
      - EUPL (European Union Public Licence): resource/E500
      - MIT: resource/E504
      - RightsStatements.org: resource/E505
    - Media Type:
      - BibTeX: resource/E420
      - CSV: resource/E402
      - DataCite Metadata Schema: resource/E416
      - EndNote: resource/E423
      - GeoJSON: resource/E408
      - GeoTIFF: resource/E407
      - HTML: resource/E424
      - JPG: resource/E404
      - JSON: resource/E401
      - MARC21: resource/E1027
      - MARCXML: resource/E419
      - MP3: resource/E412
      - MP4: resource/E414
      - PDF: resource/E410
      - PNG: resource/E405
      - RDF : resource/E417
      - RDF/XML: resource/E418
      - RIS: resource/E421
      - RTF: resource/E425
      - RefWorks: resource/E422
      - SVG: resource/E409
      - TEI: resource/E1017
      - TEX: resource/E426
      - TIFF: resource/E406
      - TSV: resource/E403
      - TXT: resource/E411
      - WAV: resource/E413
      - WebVTT: resource/E415
      - XML: resource/E400
    - Organization:
      - Bayerische Staatsbibliothek: resource/E712
      - Deutsches Museum: resource/E715
      - Digicult: resource/E711
      - Digitale Interview-Sammlungen: resource/E709
      - FIZ Karlsruhe – Leibniz-Institut für Informationsinfrastruktur: resource/E713
      - FernUniversität in Hagen: resource/E707
      - FernUniversität in Hagen, Institut für Geschichte und Biographie: resource/E708
      - Freie Universität Berlin: resource/E705
      - Institut für Zeitgeschichte : resource/E700
      - Landesarchiv Baden-Württemberg: resource/E714
      - Leibniz-Rechenzentrum (LRZ) der Bayerischen Akademie der Wissenschaften: resource/E710
      - National Research Data Infrastructure: resource/E1
      - Servicecenter eSciences (SeS): resource/E704
      - Sächsische Landesbibliothek - Staats- und Universitätsbibliothek: resource/E701
      - Task Area 1 - Data Quality: resource/E7771
      - Task Area 2 - Data Connectivity: resource/E7772
      - Task Area 3 - Data Services: resource/E7773
      - Task Area 4 - Data Literacy: resource/E7774
      - Task Area 5 - Data Culture: resource/E7775
      - Task Area 6 - Participation and Steering: resource/E7776
      - Universität Trier: resource/E703
      - Universität Trier, Fachbereich III Alte Geschichte: resource/E702
      - Universitätsbibliothek der Freien Universität Berlin: resource/E706
    - Person:
      - Almut Leh: resource/E611
      - Ansgar Schmitz: resource/E608
      - Axel Vitzthum: resource/E616
      - Charlotte Schubert: resource/E602
      - Cord Pagenstecher: resource/E610
      - Dominik Stoltz: resource/E601
      - Gregor Horstkemper: resource/E618
      - Helmut Hilz: resource/E621
      - Herdis Kley: resource/E612
      - Jan Ludwig: resource/E604
      - Johannes Bracht: resource/E617
      - Johannes Meerwald: resource/E600
      - Johannes Munke: resource/E615
      - Julia Gebhardt: resource/E605
      - Marina Lemaire: resource/E603
      - Moritz Friesenhausen: resource/E620
      - Peter Albertz: resource/E606
      - Peter Kompiel: resource/E613
      - Stefan Kellendonk: resource/E609
      - Stephan Hachinger: resource/E614
      - Wiebke Herr: resource/E619
      - Yvonne Rommelfanger: resource/E607
    - Programming Language:
      - Java : resource/E2011
      - JavaScript: resource/E2018
      - PHP: resource/E2017
      - Python: resource/E2006
      - Shell Script: resource/E2013
    - Project:
      - Fachinformationsdienst Geschichtswissenschaft: resource/E3335
      - Forschungsdatenrepositorium Trier (FRET): resource/E3331
      - LRZ FAIR Data Portal: resource/E3334
      - Oral-History.Digital. Interviewportal - Erschließungsplattform - Forschungsumgebung: resource/E3333
      - Virtuelles Datenrepositorium ViDa: resource/E3332
    - Publication&Dissemination:
      - FuD. Virtuelle Forschungsumgebung für die Geistes- und Sozialwissenschaften: resource/E107
    - Service:
      - Leibniz-Rechenzentrum (LRZ) FAIR Data Portal: resource/E109
      - Oral-History.Digital. Interviewportal - Erschließungsplattform - Forschungsumgebung: resource/E108
      - xTree Vokabularverwaltung für 200+ Vokabulare/Teilvokabulare: resource/E110
    - Software:
      - FuD. Virtuelle Forschungsumgebung für die Geistes- und Sozialwissenschaften: resource/E106
      - Oral-History.Digital. Interviewportal - Erschließungsplattform - Forschungsumgebung: resource/E108
      - Virtuelles Datenrepositorium ViDa: resource/E104
      - xTree Vokabularverwaltung für 200+ Vokabulare/Teilvokabulare: resource/E110
    - Standard:
      - AAT: resource/E1023
      - ASEQ: resource/E1028
      - CMDI: resource/E1020
      - COAR: resource/E1010
      - DDC: resource/E1032
      - DFG Science Classification: resource/E1015
      - DStatis-Fachsystematik: resource/E1016
      - DataCite: resource/E1013
      - DataCite Metadata Schema: resource/E416
      - EAC: resource/E1002
      - EAD: resource/E1001
      - FRBR: resource/E1030
      - GND ID: resource/E1009
      - GeoNames: resource/E1025
      - ICONCLASS: resource/E1024
      - ISO 25964-1: resource/E1021
      - ISO 639-2/T: resource/E1011
      - ISO 8601: resource/E1014
      - LIDO: resource/E1019
      - MARC21: resource/E1027
      - Mimetype: resource/E1012
      - OSM: resource/E1018
      - Oberbegriffsdatei: resource/E1022
      - RDA: resource/E1029
      - RDF : resource/E417
      - RVK: resource/E1031
      - RiC: resource/E1003
      - SKOS: resource/E1004
      - Schema: resource/E1000
      - TEI: resource/E1017
      - TLG ID: resource/E1008
      - TMS: resource/E1006
      - WMS: resource/E1005
      - Web Coverage Service (WCS): resource/E1007
      - Wikidata: resource/E1026
    - Storage Preservation:
      - FuD. Virtuelle Forschungsumgebung für die Geistes- und Sozialwissenschaften: resource/E107
    - Technological Means:
      - Angular: resource/E2020
      - Apache Ant: resource/E2012
      - Apache HTTP: resource/E2016
      - COinS: resource/E2028
      - Cesium: resource/E2004
      - Elasticsearch: resource/E2005
      - GraphQL: resource/E2000
      - HTML: resource/E2022
      - MariaDB: resource/E2015
      - MySQL: resource/E2014
      - OAI-PMH: resource/E2001
      - PostGIS: resource/E2009
      - PostgreSQL: resource/E2008
      - REST API: resource/E2010
      - RSS: resource/E2029
      - React: resource/E2003
      - SPARQL: resource/E2002
      - Search/Retrieve via URL: resource/E2025
      - Spring: resource/E2021
      - TYPO3: resource/E2007
      - TypeScript: resource/E2023
      - VuFind: resource/E2027
      - Z39.50: resource/E2026
      - jQuery: resource/E2019
      - webAPI (RESTful API): resource/E2024
    - Intended Purpose:
      - analysis: resource/E211
      - collaboration: resource/E217
      - collection: resource/E209
      - consulting: resource/E214
      - crowdsourcing: resource/E218
      - description: resource/E201
      - documentation: resource/E215
      - georeferencing: resource/E203
      - indexing: resource/E216
      - linking: resource/E200
      - preservation: resource/E208
      - processing: resource/E210
      - publication: resource/E212
      - research: resource/E205
      - search: resource/E204
      - storage: resource/E207
      - teaching: resource/E213
      - text analysis: resource/E206
    - Object Type:
      - annotation: resource/E302
      - audio: resource/E308
      - controlled vocabulary: resource/E301
      - data: resource/E311
      - image: resource/E306
      - map: resource/E303
      - metadata: resource/E300
      - object: resource/E307
      - simulation output: resource/E310
      - text: resource/E305
      - topographic map: resource/E304
      - video: resource/E309
    - Defined Term:
      - Alte Geschichte: resource/E804
      - Angular: resource/E2020
      - Apache 2.0: resource/E503
      - Apache Ant: resource/E2012
      - Apache HTTP: resource/E2016
      - Archivwissenschaften: resource/E801
      - BibTeX: resource/E420
      - COinS: resource/E2028
      - CSV: resource/E402
      - Cesium: resource/E2004
      - Creative Commons: resource/E502
      - Creative Commons CC0: resource/E501
      - DataCite Metadata Schema: resource/E416
      - Digital Humanities: resource/E803
      - EUPL (European Union Public Licence): resource/E500
      - Elasticsearch: resource/E2005
      - EndNote: resource/E423
      - Forschungsdatenmanagement: resource/E805
      - Geistes- und Sozialwissenschaften: resource/E806
      - GeoJSON: resource/E408
      - GeoTIFF: resource/E407
      - Geowissenschaften: resource/E802
      - Geschichte: resource/E800
      - GraphQL: resource/E2000
      - HTML: resource/E2022
      - HTML: resource/E424
      - JPG: resource/E404
      - JSON: resource/E401
      - Java : resource/E2011
      - JavaScript: resource/E2018
      - Leibniz Association: resource/E3001
      - MARCXML: resource/E419
      - MIT: resource/E504
      - MP3: resource/E412
      - MP4: resource/E414
      - MariaDB: resource/E2015
      - MySQL: resource/E2014
      - OAI-PMH: resource/E2001
      - PDF: resource/E410
      - PHP: resource/E2017
      - PNG: resource/E405
      - PostGIS: resource/E2009
      - PostgreSQL: resource/E2008
      - Python: resource/E2006
      - RDF : resource/E417
      - RDF/XML: resource/E418
      - REST API: resource/E2010
      - RIS: resource/E421
      - RSS: resource/E2029
      - RTF: resource/E425
      - React: resource/E2003
      - RefWorks: resource/E422
      - RightsStatements.org: resource/E505
      - SPARQL: resource/E2002
      - SVG: resource/E409
      - Search/Retrieve via URL: resource/E2025
      - Shell Script: resource/E2013
      - Spring: resource/E2021
      - TEX: resource/E426
      - TIFF: resource/E406
      - TSV: resource/E403
      - TXT: resource/E411
      - TYPO3: resource/E2007
      - TypeScript: resource/E2023
      - VuFind: resource/E2027
      - WAV: resource/E413
      - WebVTT: resource/E415
      - XML: resource/E400
      - Z39.50: resource/E2026
      - academic library: resource/E3002
      - analysis: resource/E211
      - annotation: resource/E302
      - audio: resource/E308
      - collaboration: resource/E217
      - collection: resource/E209
      - consulting: resource/E214
      - controlled vocabulary: resource/E301
      - crowdsourcing: resource/E218
      - data: resource/E311
      - data center: resource/E3007
      - description: resource/E201
      - documentation: resource/E215
      - faculty: resource/E3003
      - georeferencing: resource/E203
      - image: resource/E306
      - indexing: resource/E216
      - jQuery: resource/E2019
      - library: resource/E3008
      - linking: resource/E200
      - map: resource/E303
      - metadata: resource/E300
      - museum: resource/E3009
      - object: resource/E307
      - preservation: resource/E208
      - processing: resource/E210
      - publication: resource/E212
      - research: resource/E205
      - research institute: resource/E3000
      - search: resource/E204
      - simulation output: resource/E310
      - state archive: resource/E3005
      - storage: resource/E207
      - teaching: resource/E213
      - text: resource/E305
      - text analysis: resource/E206
      - topographic map: resource/E304
      - university: resource/E3004
      - university institute: resource/E3006
      - video: resource/E309
      - webAPI (RESTful API): resource/E2024
